### PR TITLE
Add \ operator and inv function

### PR DESCRIPTION
**Pull request by andreasnoack**
These definitions are useful when computing the LU of a matrix of `SymPy.Sym`s.

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks! I had to hand merge these (5bb1aef03f2e3fee0911f27866417d8d3a6e6587), as I just saw them. I hope I didn't miss any of your tests.

**Comment by andreasnoack** [comment]
No problem. Thanks for merging. As I wrote in the pr message, these changes make it possible to calculate the LU of a `Matrix{Sym}` with our generic LU and therefore `inv` works. I can see that you are also wrapping linear algebra from SymPy so I'd just wanted to mention that e.g. our `det` also works with `Matrix{Sym}`. You can try that with 
```julia
julia> det(lufact(A))`
```

**Comment by jverzani** [comment]
I'd really like to use the generic functions you have written with SymPy and add only those from SymPy that are not otherwise available.  When I remove `sympy.det ` I get this error though:  

```
julia> a
2x2 Array{Sym,2}
⎡1  x⎤
⎢    ⎥
⎣x  2⎦
julia> det(lufact(a))
ERROR: type: non-boolean (Sym) used in boolean context
julia> det(lufact(a, pivot=false))
   2    
- x  + 2
```

I need to track this down. I think I am overloading `<`  incorrectly when there are symbols involved.

**Comment by andreasnoack** [comment]
I've just changed our LU last week to only use pivoting when the elements are floating points. Therefore this only works on latest master, so you might want to keep the SymPy `det` until 0.4 is out.

This reminds me that it might be a problem that `==` is defined for `Sym`s to return something like restriction instead of a boolean. I don't know enough about SymPy to say if that is wrong, but it could be a problem for some of the generic linear algebra methods. Have you thought about using another operator to use for the special SymPy operation?

**Comment by jverzani** [comment]
Thanks, I made det conditional on the version number.

As for ==, I changed that recently so that == falls back to python's idea
of equality, which does return a boolean. This was so hashing would work. I
now have \Equal<tab> for symbolic equality (Eq). However, I see that <
isn't right, as it is doing symbolic less than (Lt in SymPy). I'll have to
see what is right there.

Thanks again for your help with this!

John

On Tue, Feb 24, 2015 at 6:15 AM, Andreas Noack <notifications@github.com>
wrote:

> I've just changed our LU last week to only use pivoting when the elements
> are floating points. Therefore this only works on latest master, so you
> might want to keep the SymPy det until 0.4 is out.
>
> This reminds me that it might be a problem that == is defined for Syms to
> return something like restriction instead of a boolean. I don't know enough
> about SymPy to say if that is wrong, but it could be a problem for some of
> the generic linear algebra methods. Have you thought about using another
> operator to use for the special SymPy operation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/pull/25#issuecomment-75738649>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Pull request closed without merging**
