### PR TITLE
Fix test on travis and appveyor .

### PR DESCRIPTION
**Pull request by dhoegh**
This is a test to see if I can get travis and appveyor working.

### CODE REVIEW

**Comment by dhoegh** [comment]
Travis and Appveyor seem to pass now. Ping me if I should squash the commits or or change anything.

**Comment by dhoegh** [comment]
I have squashed the commit.

**Comment by dhoegh** [comment]
This do also fix #36.

**Comment by jverzani** [comment]
This is so appreciated! Thanks!!

**Comment by dhoegh** [comment]
No problem. It took some time to get Appveyor/Travis running on one of my own packages with a python dependency. But now I got the hang of it.

**Pull request merged**
